version: '3'

services:
  app:
    build: .
    image: nette-sandbox
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      NETTE_DEBUG_SECRET: iFn2TBhcDrHyFJMW

  myDB:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posobota
    volumes:
      - .data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 3000:8080